# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataInicio', models.DateTimeField()),
                ('dataFinal', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validacao', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(max_length=11)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.CharField(max_length=128)),
                ('valor', models.FloatField(max_length=128)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Pessoa'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Ticket'),
        ),
    ]
